version: "3.8"

services:
  life-science:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - life-net

  postgres-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=life_user
      - POSTGRES_PASSWORD=life_pass123
      - POSTGRES_DB=life_science_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - life-net

networks:
  life-net:
    driver: bridge

volumes:
  pg-data:
